//! Gateway topic subscriptions — how a creature pushes updates to a
//! long-lived connection that is not a Caspar user.
//!
//! The node already has two fan-out paths, and neither fits an external
//! program holding a socket open: `signal_user` addresses a creature by id,
//! and `signal_store` resolves a store's members from their access grants.
//! Both need the receiver to *be* a creature with a username, because that is
//! how the signaler decides where a packet goes (and whether it must be
//! federated). A bridge running inside a VM — the crewAI bridge in a Modal
//! sandbox, say — is not a creature and has no key; it authenticates with a
//! bearer token its owning creature minted.
//!
//! So subscriptions are their own registry:
//!
//! ```text
//!   creature ── registerBridgeToken ──► grant  (token hash → topics, owner)
//!   bridge   ── /gateway/subscribe ───► subscriber bound to a socket
//!   creature ── publishUpdate ────────► every subscriber of that topic
//! ```
//!
//! Three properties are deliberate:
//!
//! * **A topic has exactly one owning creature.** It is recorded when the
//!   grant is minted, and `publish` refuses anyone else — otherwise any
//!   creature could push arbitrary packets into another's bridge.
//! * **Delivery never blocks the publisher.** A sink hands the frame to the
//!   connection's own outbound queue and returns; a creature publishing to a
//!   slow consumer is not stalled by it.
//! * **Dead subscribers are reaped, not accumulated.** A sink reports whether
//!   the connection is still live, and a subscriber whose connection has gone
//!   is dropped on the next publish — a bridge that reconnects (a sandbox
//!   restart) must not leave its predecessor behind forever.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, RwLock};

use aseman_domain::Uuid;
use aseman_domain::realtime::{Event, RetentionClass};
use aseman_ports::realtime::{EventLog, Publication};
use aseman_ports::{PortError, PortResult};
use dashmap::DashMap;
use once_cell::sync::Lazy;
use serde_json::Value;
use sha2::{Digest, Sha256};

use crate::api::workloads::creature_subject;

/// Writes one update frame to a subscriber's connection.
///
/// Returns `false` when the connection is gone, which is what lets `publish`
/// reap it. Implementations must not block: the WS driver's sink pushes onto
/// the socket's outbound channel, which the I/O thread drains.
pub type SubscriberSink = Arc<dyn Fn(&str, &Value) -> bool + Send + Sync>;

/// One connected subscriber.
pub struct Subscriber {
    /// Connection-scoped id, generated by the transport that owns the socket.
    pub id: String,
    /// The creature whose grant this subscriber authenticated with. Recorded
    /// so a publish can be attributed and a revoked grant traced back.
    #[expect(
        dead_code,
        reason = "RL-008: process-local subscriber surface kept for rollback"
    )]
    pub creature_id: String,
    /// Topics this subscriber receives.
    pub topics: Vec<String>,
    pub sink: SubscriberSink,
}

#[derive(Default)]
struct Registry {
    /// topic → subscriber ids
    by_topic: DashMap<String, DashMap<String, ()>>,
    /// subscriber id → subscriber
    subscribers: DashMap<String, Arc<Subscriber>>,
    delivered: AtomicU64,
    dropped: AtomicU64,
}

static REGISTRY: Lazy<Registry> = Lazy::new(Registry::default);
static EVENT_LOG: Lazy<RwLock<Option<Arc<dyn EventLog>>>> = Lazy::new(|| RwLock::new(None));

/// Install the authoritative A707 log. The public listener and bridge publisher use
/// the same provider; legacy socket fan-out remains a compatibility side effect.
pub fn configure_event_log(event_log: Arc<dyn EventLog>) {
    *EVENT_LOG
        .write()
        .unwrap_or_else(|poisoned| poisoned.into_inner()) = Some(event_log);
}

/// Register a subscriber against every topic it was granted.
///
/// Re-subscribing under the same id replaces the previous registration
/// wholesale (topics included), so a bridge that re-subscribes with a narrower
/// set is not still receiving the wider one.
pub fn subscribe(subscriber: Subscriber) {
    let id = subscriber.id.clone();
    unsubscribe(&id);
    let subscriber = Arc::new(subscriber);
    for topic in &subscriber.topics {
        REGISTRY
            .by_topic
            .entry(topic.clone())
            .or_default()
            .insert(id.clone(), ());
    }
    REGISTRY.subscribers.insert(id, subscriber);
}

/// Drop a subscriber and every topic index entry pointing at it. Called when
/// its connection closes and by `subscribe` before a re-registration.
pub fn unsubscribe(subscriber_id: &str) {
    let Some((_, subscriber)) = REGISTRY.subscribers.remove(subscriber_id) else {
        return;
    };
    for topic in &subscriber.topics {
        let mut now_empty = false;
        if let Some(entry) = REGISTRY.by_topic.get(topic) {
            entry.remove(subscriber_id);
            now_empty = entry.is_empty();
        }
        // A topic nobody subscribes to must not keep a permanent empty entry:
        // topics are creature-supplied strings, so leaving them behind is an
        // unbounded, externally-driven leak.
        if now_empty {
            REGISTRY
                .by_topic
                .remove_if(topic, |_, subs| subs.is_empty());
        }
    }
}

fn append_durable(
    event_log: &dyn EventLog,
    topic: &str,
    creature_id: &str,
    key: &str,
    data: &Value,
) -> PortResult<()> {
    if topic.is_empty() || topic.len() > 256 {
        return Err(PortError::Failed(
            "realtime topic must be 1-256 bytes".to_owned(),
        ));
    }
    let payload = serde_json::to_vec(data).map_err(|error| PortError::Failed(error.to_string()))?;
    let payload_digest = format!("sha256:{}", hex::encode(Sha256::digest(&payload)));
    let event_id = Uuid::now_v7();
    let creature_id = creature_subject(creature_id).id;

    // Sequence allocation is optimistic across replicas. A conflicting writer wins;
    // this producer reads the new bound and retries without ever creating a gap.
    for _ in 0..32 {
        let (latest, _) = event_log.bounds(topic)?;
        let publication = Publication {
            event: Event {
                id: event_id,
                stream: topic.to_owned(),
                creature_id,
                kind: key.to_owned(),
                producer: "guest.bridge.publish".to_owned(),
                sequence: latest.unwrap_or(0).saturating_add(1),
                at_millis: chrono::Utc::now().timestamp_millis(),
                payload_digest: payload_digest.clone(),
                retention: RetentionClass::Standard,
                version: "1".to_owned(),
                idempotency_key: None,
            },
            payload: payload.clone(),
        };
        match event_log.append(&publication) {
            Ok(()) => return Ok(()),
            Err(PortError::Conflict) => continue,
            Err(error) => return Err(error),
        }
    }
    Err(PortError::Conflict)
}

/// Durably append one update, then push it to every legacy subscriber of `topic`.
/// Returns how many compatibility connections it reached.
pub fn publish(topic: &str, creature_id: &str, key: &str, data: &Value) -> PortResult<usize> {
    let event_log = EVENT_LOG
        .read()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .clone();
    if let Some(event_log) = event_log {
        append_durable(event_log.as_ref(), topic, creature_id, key, data)?;
    }

    let Some(entry) = REGISTRY.by_topic.get(topic) else {
        return Ok(0);
    };
    let ids: Vec<String> = entry.iter().map(|e| e.key().clone()).collect();
    drop(entry);

    let mut delivered = 0usize;
    let mut dead: Vec<String> = Vec::new();
    for id in ids {
        let Some(subscriber) = REGISTRY.subscribers.get(&id).map(|e| e.value().clone()) else {
            dead.push(id);
            continue;
        };
        if (subscriber.sink)(key, data) {
            delivered += 1;
        } else {
            dead.push(id);
        }
    }
    for id in dead {
        REGISTRY.dropped.fetch_add(1, Ordering::Relaxed);
        unsubscribe(&id);
    }
    REGISTRY
        .delivered
        .fetch_add(delivered as u64, Ordering::Relaxed);
    Ok(delivered)
}

/// How many connections currently subscribe to `topic`.
#[cfg_attr(
    not(test),
    expect(
        dead_code,
        reason = "RL-008: process-local subscriber surface kept for rollback"
    )
)]
pub fn subscriber_count(topic: &str) -> usize {
    REGISTRY
        .by_topic
        .get(topic)
        .map(|entry| entry.len())
        .unwrap_or(0)
}

/// Counters for the node's health/telemetry surface.
#[expect(
    dead_code,
    reason = "RL-008: process-local subscriber surface kept for rollback"
)]
pub fn stats() -> Value {
    serde_json::json!({
        "topics": REGISTRY.by_topic.len(),
        "subscribers": REGISTRY.subscribers.len(),
        "delivered": REGISTRY.delivered.load(Ordering::Relaxed),
        "dropped": REGISTRY.dropped.load(Ordering::Relaxed),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;
    use std::sync::atomic::AtomicUsize;

    #[derive(Default)]
    struct RecordingEventLog {
        publications: Mutex<Vec<Publication>>,
    }

    impl EventLog for RecordingEventLog {
        fn append(&self, publication: &Publication) -> PortResult<()> {
            let mut publications = self.publications.lock().unwrap();
            let expected = publications
                .last()
                .map_or(1, |item| item.event.sequence + 1);
            if publication.event.sequence != expected {
                return Err(PortError::Conflict);
            }
            publications.push(publication.clone());
            Ok(())
        }

        fn read(&self, _stream: &str, after: u64, limit: usize) -> PortResult<Vec<Publication>> {
            Ok(self
                .publications
                .lock()
                .unwrap()
                .iter()
                .filter(|item| item.event.sequence > after)
                .take(limit)
                .cloned()
                .collect())
        }

        fn bounds(&self, _stream: &str) -> PortResult<(Option<u64>, Option<u64>)> {
            let publications = self.publications.lock().unwrap();
            Ok((
                publications.last().map(|item| item.event.sequence),
                publications.first().map(|item| item.event.sequence),
            ))
        }

        fn purge_expired(&self, _now_millis: i64) -> PortResult<u64> {
            Ok(0)
        }
    }

    fn counting_sink(hits: Arc<AtomicUsize>, alive: bool) -> SubscriberSink {
        Arc::new(move |_key: &str, _data: &Value| {
            hits.fetch_add(1, Ordering::Relaxed);
            alive
        })
    }

    #[test]
    fn publish_reaches_only_subscribers_of_the_topic() {
        let hits = Arc::new(AtomicUsize::new(0));
        subscribe(Subscriber {
            id: "sub-a".into(),
            creature_id: "creature-1".into(),
            topics: vec!["space:1".into()],
            sink: counting_sink(hits.clone(), true),
        });
        assert_eq!(
            publish("space:1", "creature-1", "crew/update", &Value::Null),
            Ok(1)
        );
        assert_eq!(
            publish("space:2", "creature-1", "crew/update", &Value::Null),
            Ok(0)
        );
        assert_eq!(hits.load(Ordering::Relaxed), 1);
        unsubscribe("sub-a");
    }

    #[test]
    fn a_dead_connection_is_reaped_on_publish() {
        let hits = Arc::new(AtomicUsize::new(0));
        subscribe(Subscriber {
            id: "sub-dead".into(),
            creature_id: "creature-1".into(),
            topics: vec!["space:dead".into()],
            sink: counting_sink(hits.clone(), false),
        });
        assert_eq!(
            publish("space:dead", "creature-1", "k", &Value::Null),
            Ok(0)
        );
        // The failed write removed it, so the topic index is empty and a
        // second publish does not even attempt delivery.
        assert_eq!(subscriber_count("space:dead"), 0);
        assert_eq!(
            publish("space:dead", "creature-1", "k", &Value::Null),
            Ok(0)
        );
        assert_eq!(hits.load(Ordering::Relaxed), 1);
    }

    #[test]
    fn durable_publish_uses_a707_scope_sequence_and_digest() {
        let event_log = RecordingEventLog::default();
        let payload = serde_json::json!({"answer": 42});
        append_durable(
            &event_log,
            "space:durable",
            "7@global",
            "crew/update",
            &payload,
        )
        .unwrap();
        append_durable(
            &event_log,
            "space:durable",
            "7@global",
            "crew/update",
            &payload,
        )
        .unwrap();

        let publications = event_log.publications.lock().unwrap();
        assert_eq!(publications.len(), 2);
        assert_eq!(publications[0].event.sequence, 1);
        assert_eq!(publications[1].event.sequence, 2);
        assert_eq!(
            publications[0].event.creature_id,
            creature_subject("7@global").id
        );
        assert_eq!(publications[0].event.stream, "space:durable");
        assert_eq!(publications[0].event.kind, "crew/update");
        assert_eq!(
            publications[0].payload,
            serde_json::to_vec(&payload).unwrap()
        );
        assert!(publications[0].event.payload_digest.starts_with("sha256:"));
    }

    #[test]
    fn resubscribing_replaces_the_previous_topic_set() {
        let hits = Arc::new(AtomicUsize::new(0));
        subscribe(Subscriber {
            id: "sub-b".into(),
            creature_id: "creature-1".into(),
            topics: vec!["space:old".into()],
            sink: counting_sink(hits.clone(), true),
        });
        subscribe(Subscriber {
            id: "sub-b".into(),
            creature_id: "creature-1".into(),
            topics: vec!["space:new".into()],
            sink: counting_sink(hits.clone(), true),
        });
        assert_eq!(subscriber_count("space:old"), 0);
        assert_eq!(subscriber_count("space:new"), 1);
        unsubscribe("sub-b");
    }
}
