use super::*;
use aseman_domain::identity::SubjectKind;
use ring::signature::KeyPair;
use serde_json::{Value, json};

const VECTORS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../contracts/security/vectors/identity-v1.json"
);

fn seed_key(seed: u8) -> Ed25519KeyPair {
    Ed25519KeyPair::from_seed_unchecked(&[seed; 32]).unwrap()
}

fn public(key: &Ed25519KeyPair) -> PublicKey {
    PublicKey::ed25519(key.public_key().as_ref().try_into().unwrap())
}

fn subject() -> Subject {
    Subject {
        kind: SubjectKind::Workload,
        id: uuid::Uuid::parse_str("0190f1a2-7b3c-7d4e-8f00-112233445566").unwrap(),
    }
}

const BODY: &[u8] = br#"{"op":"get","key":"profile"}"#;

fn proof(key: &Ed25519KeyPair) -> SignedRequestProof {
    let key_id = public(key).key_id();
    let subject = subject();
    let digest = body_digest(BODY);
    sign_ed25519(
        key,
        SignatureContext::Request,
        &SignedFields {
            algorithm: "ed25519",
            key_id: &key_id,
            key_epoch: 1,
            subject: &subject,
            audience: "node:0190f1a2-0000-7000-8000-000000000001/guest/v1",
            window: CredentialWindow {
                issued_at_millis: 1_800_000_000_000,
                not_before_millis: 1_800_000_000_000,
                expires_at_millis: 1_800_000_060_000,
            },
            nonce: &[7; 16],
            request_id: "req-1",
            action: "guest.kv.get",
            resource: "collection:profile",
            body_digest: &digest,
        },
    )
}

/// Mutations of the valid proof and the error each must produce.
fn negative_cases(
    valid: &SignedRequestProof,
) -> Vec<(&'static str, SignedRequestProof, &'static str)> {
    let with = |change: fn(&mut SignedRequestProof)| {
        let mut changed = valid.clone();
        change(&mut changed);
        changed
    };
    vec![
        ("version 2", with(|p| p.version = 2), "unsupported_version"),
        (
            "unknown algorithm",
            with(|p| p.algorithm = "hmac".into()),
            "unsupported_algorithm",
        ),
        (
            "short nonce",
            with(|p| p.nonce = "BwcHBw".into()),
            "malformed",
        ),
        (
            "uppercase subject",
            with(|p| p.subject = p.subject.to_uppercase()),
            "malformed",
        ),
        (
            "padded base64",
            with(|p| p.body_digest.push('=')),
            "malformed",
        ),
        (
            "other audience",
            with(|p| p.audience = "node:other".into()),
            "bad_signature",
        ),
        (
            "other context",
            with(|p| p.context = SignatureContext::Challenge),
            "bad_signature",
        ),
        ("other epoch", with(|p| p.key_epoch = 2), "bad_signature"),
        (
            "later expiry",
            with(|p| p.expires_at_millis += 1),
            "bad_signature",
        ),
    ]
}

fn outcome(proof: &SignedRequestProof, key: &PublicKey) -> &'static str {
    match proof
        .parse()
        .and_then(|parsed| verify_proof_signature(&parsed, key))
    {
        Ok(()) => "ok",
        Err(error) => error.code(),
    }
}

fn vectors() -> Value {
    let key = seed_key(1);
    let public = public(&key);
    let valid = proof(&key);
    let parsed = valid.parse().unwrap();
    json!({
        "description": "A401 identity-v1 vectors. Generated by the ignored aseman-contracts identity::tests::write_vectors test; never edit by hand.",
        "key": {
            "ed25519_seed_hex": hex_encode(&[1; 32]),
            "public_key_hex": hex_encode(public.key_bytes()),
            "encoding_hex": hex_encode(&public.encode()),
            "multibase": public.to_multibase(),
            "fingerprint_hex": hex_encode(&public.fingerprint()),
            "key_id": public.key_id(),
        },
        "request": {
            "body_utf8": std::str::from_utf8(BODY).unwrap(),
            "signing_input_hex": hex_encode(&signing_input(SignatureContext::Request, &proof_fields(&parsed))),
            "proof": valid,
        },
        "introduction": {
            "subject": "node:0190f1a2-0000-7000-8000-000000000002",
            "public_key_multibase": public.to_multibase(),
            "epoch": 1,
            "not_before_millis": 1_800_000_000_000_i64,
            "expires_at_millis": null,
            "bytes_hex": hex_encode(&introduction_bytes(&Introduction {
                subject: "node:0190f1a2-0000-7000-8000-000000000002".parse().unwrap(),
                public_key: public.encode(),
                epoch: 1,
                not_before_millis: 1_800_000_000_000,
                expires_at_millis: None,
            })),
        },
        "negative": negative_cases(&valid)
            .into_iter()
            .map(|(case, proof, error)| json!({"case": case, "proof": proof, "error": error}))
            .collect::<Vec<_>>(),
    })
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn expected_vectors() -> String {
    serde_json::to_string_pretty(&vectors()).unwrap() + "\n"
}

/// Regenerate the contract file: `cargo test -p aseman-contracts identity -- --ignored`.
#[test]
#[ignore = "writes contracts/security/vectors/identity-v1.json"]
fn write_vectors() {
    std::fs::write(VECTORS, expected_vectors()).unwrap();
}

#[test]
fn vectors_match_the_contract_file() {
    let committed = std::fs::read_to_string(VECTORS).expect(
        "contracts/security/vectors/identity-v1.json (regenerate with the ignored write_vectors test)",
    );
    assert_eq!(
        committed,
        expected_vectors(),
        "A401 vectors drifted from the code"
    );
}

#[test]
fn committed_vectors_verify_and_fail_with_their_codes() {
    let file: Value = serde_json::from_str(&std::fs::read_to_string(VECTORS).unwrap()).unwrap();
    let key = PublicKey::from_multibase(file["key"]["multibase"].as_str().unwrap()).unwrap();
    assert_eq!(key.key_id(), file["key"]["key_id"]);
    let valid: SignedRequestProof =
        serde_json::from_value(file["request"]["proof"].clone()).unwrap();
    assert_eq!(outcome(&valid, &key), "ok");
    assert_eq!(
        hex_encode(&valid.parse().unwrap().body_digest),
        hex_encode(&body_digest(
            file["request"]["body_utf8"].as_str().unwrap().as_bytes()
        ))
    );
    for case in file["negative"].as_array().unwrap() {
        let proof: SignedRequestProof = serde_json::from_value(case["proof"].clone()).unwrap();
        assert_eq!(outcome(&proof, &key), case["error"], "{}", case["case"]);
    }
}

#[test]
fn keys_have_one_encoding_and_one_text() {
    let key = public(&seed_key(2));
    let encoded = key.encode();
    assert_eq!(encoded[..3], [KEY_ENCODING_VERSION, 0xed, 0x01]);
    assert_eq!(PublicKey::decode(&encoded), Ok(key.clone()));
    assert_eq!(
        PublicKey::from_multibase(&key.to_multibase()),
        Ok(key.clone())
    );
    assert!(key.to_multibase().starts_with('z'));
    assert!(is_key_id(&key.key_id()));
    assert!(!is_key_id(&key.to_multibase()));
    let mut other_version = encoded.clone();
    other_version[0] = 2;
    assert_eq!(
        PublicKey::decode(&other_version),
        Err(AuthenticationError::UnsupportedVersion)
    );
    assert_eq!(
        PublicKey::decode(&encoded[..encoded.len() - 1]),
        Err(AuthenticationError::Malformed)
    );
    assert_eq!(
        PublicKey::decode(&[KEY_ENCODING_VERSION, 0x00, 0x01]),
        Err(AuthenticationError::UnsupportedAlgorithm)
    );
    // A leading `1` spells another value (a leading zero byte, so another version),
    // and other multibase prefixes are rejected.
    assert_eq!(
        PublicKey::from_multibase(&format!("z1{}", &key.to_multibase()[1..])),
        Err(AuthenticationError::UnsupportedVersion)
    );
    assert_eq!(
        PublicKey::from_multibase(&key.to_multibase().replacen('z', "f", 1)),
        Err(AuthenticationError::Malformed)
    );
}

#[test]
fn a_proof_verifies_only_with_the_named_key() {
    let key = seed_key(3);
    let valid = proof(&key);
    let parsed = valid.parse().unwrap();
    assert_eq!(verify_proof_signature(&parsed, &public(&key)), Ok(()));
    assert_eq!(
        verify_proof_signature(&parsed, &public(&seed_key(4))),
        Err(AuthenticationError::UnknownKey)
    );
    let mut tampered = valid.clone();
    tampered.signature = URL_SAFE_NO_PAD.encode([0u8; 64]);
    assert_eq!(
        verify_proof_signature(&tampered.parse().unwrap(), &public(&key)),
        Err(AuthenticationError::BadSignature)
    );
    let mut unknown_field = serde_json::to_value(&valid).unwrap();
    unknown_field["extra"] = json!(1);
    assert!(serde_json::from_value::<SignedRequestProof>(unknown_field).is_err());
}

#[test]
fn legacy_rsa_keys_verify_pss_signatures_of_the_canonical_structure() {
    use rsa::pkcs8::EncodePublicKey;
    use rsa::pss::BlindedSigningKey;
    use rsa::signature::{RandomizedSigner, SignatureEncoding};
    let private = rsa::RsaPrivateKey::new(&mut rsa::rand_core::OsRng, 1024).unwrap();
    let der = private.to_public_key().to_public_key_der().unwrap();
    let key = PublicKey::legacy_rsa(der.as_bytes()).unwrap();
    assert!(key.algorithm().is_legacy());
    assert_eq!(PublicKey::decode(&key.encode()), Ok(key.clone()));
    let key_id = key.key_id();
    let subject = Subject {
        kind: SubjectKind::Creature,
        ..subject()
    };
    let digest = body_digest(b"");
    let fields = SignedFields {
        algorithm: "rsa-pss-sha256",
        key_id: &key_id,
        key_epoch: 0,
        subject: &subject,
        audience: "node:a",
        window: CredentialWindow {
            issued_at_millis: 1,
            not_before_millis: 1,
            expires_at_millis: 2,
        },
        nonce: &[1; 16],
        request_id: "r",
        action: "a",
        resource: "",
        body_digest: &digest,
    };
    let signature = BlindedSigningKey::<Sha256>::new(private)
        .sign_with_rng(
            &mut rsa::rand_core::OsRng,
            &signing_input(SignatureContext::Challenge, &fields),
        )
        .to_vec();
    let message = signing_input(SignatureContext::Challenge, &fields);
    assert_eq!(key.verify(&message, &signature), Ok(()));
    assert_eq!(
        key.verify(
            &signing_input(SignatureContext::Request, &fields),
            &signature
        ),
        Err(AuthenticationError::BadSignature)
    );
}
