// @generated by `asemanctl vms sync` — DO NOT EDIT BY HAND.
//
// Regenerated by `asemanctl vms sync`. It imports each VM plugin project
// enabled in `modules/runtime/` and registers it with the aseman-vm-sdk
// plugin registry, so the native VMM backend carries exactly the VM types
// the host admin selected — without its source ever naming them.

use std::sync::Once;

static REGISTER: Once = Once::new();

/// Register every compiled VM plugin `enabled` accepts with the VMM plugin
/// registry, each configured from `config`. Idempotent — safe to call from
/// multiple init paths; the first call wins.
pub fn register_all(config: &aseman_config::RuntimeConfig, enabled: &dyn Fn(&str) -> bool) {
    REGISTER.call_once(|| {
        if enabled("docker") {
            aseman_vm_docker::register(config);
        }
        if enabled("elpian") {
            aseman_vm_elpian::register(config);
        }
        if enabled("elpify") {
            aseman_vm_elpify::register(config);
        }
        if enabled("fire") {
            aseman_vm_fire::register(config);
        }
        if enabled("javascript") {
            aseman_vm_javascript::register(config);
        }
        if enabled("modal") {
            aseman_vm_modal::register(config);
        }
        if enabled("wasm") {
            aseman_vm_wasm::register(config);
        }
    });
}

/// The VM plugin keys compiled into this build.
pub fn enabled_vm_keys() -> Vec<&'static str> {
    vec![
        "docker",
        "elpian",
        "elpify",
        "fire",
        "javascript",
        "modal",
        "wasm",
    ]
}
