#!/usr/bin/env python3
"""Check the repository hierarchy against its contract and render the report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts" / "repository" / "layout.json"
OUTPUT = ROOT / "docs" / "generated" / "repository-layout.md"


def row(path: str, expected: str) -> str:
    present = (ROOT / path).exists()
    state = "PRESENT" if present else "OPEN"
    return f"| `{path}` | {expected} | {state} |"


def render() -> str:
    contract = json.loads(SOURCE.read_text())
    lines = [
        "---",
        "status: GENERATED",
        "owner: architecture",
        "source_of_truth: contracts/repository/layout.json",
        "verification: python3 scripts/generate_repository_layout.py --check",
        "---",
        "",
        "# Repository hierarchy",
        "",
        "> Generated by `scripts/generate_repository_layout.py`. Do not edit by hand.",
        "",
        "Every listed path must be present; a forbidden root must be absent.",
        "",
        "| Path | Expected ownership | State |",
        "|---|---|---|",
    ]
    lines.extend(row(path, "root file") for path in contract["required_files"])
    lines.extend(row(path, "ownership root") for path in contract["ownership_roots"])
    lines.extend(row(path, "package") for path in contract["packages"])
    lines.extend(
        f"| `{path}` | forbidden root | {'PRESENT' if (ROOT / path).exists() else 'ABSENT'} |"
        for path in contract["forbidden_roots"]
    )
    lines.append("")
    return "\n".join(lines)


def violations() -> list[str]:
    contract = json.loads(SOURCE.read_text())
    expected = contract["required_files"] + contract["ownership_roots"] + contract["packages"]
    missing = [f"missing: {path}" for path in expected if not (ROOT / path).exists()]
    forbidden = [f"forbidden: {path}" for path in contract["forbidden_roots"] if (ROOT / path).exists()]
    return missing + forbidden


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    problems = violations()
    if problems:
        raise SystemExit("repository layout violations:\n" + "\n".join(problems))
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit("repository hierarchy report is stale")
        print("repository hierarchy report is up to date")
        return
    OUTPUT.write_text(rendered)


if __name__ == "__main__":
    main()
