#!/usr/bin/env python3
"""Generate dependency-free TypeScript and Python clients from A701 OpenAPI."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "contracts/public/openapi.json"
POLICY = ROOT / "contracts/public/client-policy.json"


def operations() -> tuple[str, list[dict[str, object]]]:
    document = json.loads(OPENAPI.read_text())
    version = str(document["info"]["version"])
    found: list[dict[str, object]] = []
    for path, path_item in sorted(document["paths"].items()):
        for method, operation in sorted(path_item.items()):
            found.append(
                {
                    "name": operation["operationId"],
                    "path": path,
                    "method": method.upper(),
                    "mutation": operation["x-aseman-class"] != "read",
                    "action": operation["x-aseman-action"],
                    "summary": operation["summary"],
                }
            )
    names = [str(item["name"]) for item in found]
    if len(names) != len(set(names)):
        raise SystemExit("public client generation: duplicate operationId")
    return version, found


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def typescript(version: str, items: list[dict[str, object]]) -> str:
    methods = []
    catalogue = []
    for item in items:
        name = item["name"]
        path = item["path"]
        mutation = "true" if item["mutation"] else "false"
        summary = str(item["summary"]).replace("*/", "* /")
        action = item["action"]
        methods.append(
            f'''  /** {summary}. Policy action: `{action}`. */
  {name}(body: JsonObject = {{}}, options: RequestOptions = {{}}): Promise<JsonValue> {{
    return this.invoke("{path}", {mutation}, body, options);
  }}'''
        )
        catalogue.append(f'  {name}: {{ path: "{path}", mutation: {mutation} }},')
    return f'''// @generated by scripts/generate_public_clients.py from contracts/public/openapi.json.
// Do not edit. Public API major: {version}.

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];
export interface JsonObject {{ [key: string]: JsonValue; }}

export interface RequestOptions {{
  session?: string;
  proof?: string;
  requestId?: string;
  idempotencyKey?: string;
  signal?: AbortSignal;
}}

export class AsemanApiError extends Error {{
  constructor(
    public readonly status: number,
    public readonly problem: JsonValue,
    public readonly requestId: string | null,
  ) {{
    super(`Aseman API request failed with HTTP ${{status}}`);
    this.name = "AsemanApiError";
  }}
}}

export const operations = {{
{chr(10).join(catalogue)}
}} as const;

export class AsemanClient {{
  constructor(
    private readonly baseUrl: string,
    private readonly defaults: RequestOptions = {{}},
  ) {{}}

  private async invoke(
    path: string,
    mutation: boolean,
    body: JsonObject,
    options: RequestOptions,
  ): Promise<JsonValue> {{
    const merged = {{ ...this.defaults, ...options }};
    if (Boolean(merged.session) === Boolean(merged.proof)) {{
      throw new TypeError("exactly one of session or proof is required");
    }}
    if (mutation && !merged.idempotencyKey) {{
      throw new TypeError("idempotencyKey is required for mutating operations");
    }}
    const headers: Record<string, string> = {{
      "accept": "application/json",
      "content-type": "application/json",
    }};
    if (merged.session) headers["Aseman-Session"] = merged.session;
    if (merged.proof) headers["Aseman-Proof"] = merged.proof;
    if (merged.requestId) headers["Aseman-Request-Id"] = merged.requestId;
    if (merged.idempotencyKey) headers["Idempotency-Key"] = merged.idempotencyKey;
    const response = await fetch(new URL(path, this.baseUrl), {{
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: merged.signal,
    }});
    const raw = await response.text();
    let decoded: JsonValue = null;
    if (raw) {{
      try {{ decoded = JSON.parse(raw) as JsonValue; }}
      catch {{ decoded = raw; }}
    }}
    if (!response.ok) {{
      throw new AsemanApiError(response.status, decoded, response.headers.get("Aseman-Request-Id"));
    }}
    return decoded;
  }}

{chr(10).join(methods)}
}}
'''


def python(version: str, items: list[dict[str, object]]) -> str:
    methods = []
    catalogue = []
    for item in items:
        py_name = snake(str(item["name"]))
        path = item["path"]
        mutation = "True" if item["mutation"] else "False"
        summary = repr(f"{item['summary']}. Policy action: {item['action']}.")
        methods.append(
            f'''    def {py_name}(self, body: JsonObject | None = None, **options: str) -> JsonValue:
        {summary}
        return self._invoke("{path}", {mutation}, body or {{}}, **options)
'''
        )
        catalogue.append(f'    "{py_name}": {{"path": "{path}", "mutation": {mutation}}},')
    return f'''# @generated by scripts/generate_public_clients.py from contracts/public/openapi.json.
# Do not edit. Public API major: {version}.
from __future__ import annotations

import json
import urllib.error
import urllib.request
from typing import Any, TypeAlias

JsonValue: TypeAlias = Any
JsonObject: TypeAlias = dict[str, JsonValue]

OPERATIONS = {{
{chr(10).join(catalogue)}
}}


class AsemanApiError(RuntimeError):
    def __init__(self, status: int, problem: JsonValue, request_id: str | None) -> None:
        super().__init__(f"Aseman API request failed with HTTP {{status}}")
        self.status = status
        self.problem = problem
        self.request_id = request_id


class AsemanClient:
    def __init__(self, base_url: str, *, session: str | None = None, proof: str | None = None, timeout: float = 30.0) -> None:
        self.base_url = base_url.rstrip("/")
        self.session = session
        self.proof = proof
        self.timeout = timeout

    def _invoke(self, path: str, mutation: bool, body: JsonObject, **options: str) -> JsonValue:
        session = options.get("session", self.session)
        proof = options.get("proof", self.proof)
        if bool(session) == bool(proof):
            raise TypeError("exactly one of session or proof is required")
        idempotency_key = options.get("idempotency_key")
        if mutation and not idempotency_key:
            raise TypeError("idempotency_key is required for mutating operations")
        headers = {{"Accept": "application/json", "Content-Type": "application/json"}}
        headers["Aseman-Session" if session else "Aseman-Proof"] = session or proof or ""
        if options.get("request_id"):
            headers["Aseman-Request-Id"] = options["request_id"]
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        request = urllib.request.Request(
            self.base_url + path,
            data=json.dumps(body, separators=(",", ":")).encode(),
            headers=headers,
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                raw = response.read()
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as error:
            raw = error.read()
            try:
                problem: JsonValue = json.loads(raw) if raw else None
            except json.JSONDecodeError:
                problem = raw.decode(errors="replace")
            raise AsemanApiError(error.code, problem, error.headers.get("Aseman-Request-Id")) from error

{chr(10).join(methods)}
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    policy = json.loads(POLICY.read_text())
    version, items = operations()
    renderers = {"typescript": typescript(version, items), "python": python(version, items)}
    errors = []
    for target in policy["generated"]:
        output = ROOT / target["path"]
        rendered = renderers[target["language"]]
        if args.check:
            if not output.exists() or output.read_text() != rendered:
                errors.append(str(output.relative_to(ROOT)))
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(rendered)
    if errors:
        raise SystemExit("generated public clients are stale: " + ", ".join(errors))
    print(f"public clients are up to date ({len(items)} operations, {len(renderers)} languages)")


if __name__ == "__main__":
    main()
