#!/usr/bin/env python3
"""Generate the canonical-versus-current repository hierarchy report (R22)."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts" / "repository" / "layout.json"
OUTPUT = ROOT / "docs" / "generated" / "repository-layout.md"


def row(path: str, expected: str) -> str:
    present = (ROOT / path).exists()
    state = "PRESENT" if present else "OPEN"
    return f"| `{path}` | {expected} | {state} |"


def render() -> str:
    contract = json.loads(SOURCE.read_text())
    lines = [
        "---",
        "status: GENERATED",
        "owner: architecture",
        "source_of_truth: contracts/repository/layout.json",
        "verification: python3 scripts/generate_repository_layout.py --check",
        "---",
        "",
        "# Repository hierarchy",
        "",
        "> Generated by `scripts/generate_repository_layout.py`. Do not edit by hand.",
        "",
        "`PRESENT` means the target path exists; it does not claim the capability's",
        "implementation or deletion gate is complete. `OPEN` is a structural gap.",
        "Legacy roots remain until their removal-ledger gates pass.",
        "",
        "| Path | Expected ownership | State |",
        "|---|---|---|",
    ]
    lines.extend(row(path, "root file") for path in contract["required_files"])
    lines.extend(row(path, "ownership root") for path in contract["ownership_roots"])
    lines.extend(row(path, "target package") for path in contract["target_packages"])
    lines.extend(row(path, "legacy root pending removal gate") for path in contract["legacy_roots"])
    target_open = sum(not (ROOT / path).exists() for path in contract["target_packages"])
    legacy_present = sum((ROOT / path).exists() for path in contract["legacy_roots"])
    lines.extend(
        [
            "",
            f"Target package paths still open: **{target_open}**.",
            f"Legacy roots still present: **{legacy_present}**.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit("repository hierarchy report is stale")
        print("repository hierarchy report is up to date")
        return
    OUTPUT.write_text(rendered)


if __name__ == "__main__":
    main()
