-- Generated by scripts/generate_postgres_storage_classes.py; do not edit by hand.
BEGIN;
CREATE SCHEMA IF NOT EXISTS aseman_storage;
REVOKE ALL ON SCHEMA aseman_storage FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS aseman_telemetry;
REVOKE ALL ON SCHEMA aseman_telemetry FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS aseman_audit;
REVOKE ALL ON SCHEMA aseman_audit FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS aseman_finance;
REVOKE ALL ON SCHEMA aseman_finance FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS aseman_outbox;
REVOKE ALL ON SCHEMA aseman_outbox FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS aseman_realtime;
REVOKE ALL ON SCHEMA aseman_realtime FROM PUBLIC;

CREATE OR REPLACE FUNCTION aseman_storage.reject_capsule_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN
  RAISE EXCEPTION 'append-only capsule rows cannot be updated or deleted' USING ERRCODE = '55000';
END $$;

CREATE TABLE IF NOT EXISTS aseman_telemetry."workload_samples" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "metric" TEXT,
  "quantity" DOUBLE PRECISION,
  "observed_at_micros" BIGINT,
  "labels" BYTEA,
  "workload" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_workload_samples_metric CHECK (tombstone OR "metric" IS NOT NULL),
  CONSTRAINT ck_live_workload_samples_quantity CHECK (tombstone OR "quantity" IS NOT NULL),
  CONSTRAINT ck_live_workload_samples_observed_at_micros CHECK (tombstone OR "observed_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_telemetry."node_health_samples" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "status" TEXT,
  "cpu_millis" BIGINT,
  "memory_bytes" BIGINT,
  "observed_at_micros" BIGINT,
  "details" BYTEA,
  "node" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_node_health_samples_status CHECK (tombstone OR "status" IS NOT NULL),
  CONSTRAINT ck_live_node_health_samples_cpu_millis CHECK (tombstone OR "cpu_millis" IS NOT NULL),
  CONSTRAINT ck_live_node_health_samples_memory_bytes CHECK (tombstone OR "memory_bytes" IS NOT NULL),
  CONSTRAINT ck_live_node_health_samples_observed_at_micros CHECK (tombstone OR "observed_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_telemetry."build_logs" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "legacy_id" TEXT,
  "build_id" TEXT,
  "machine_id" TEXT,
  "workload_id" TEXT,
  "log_type" TEXT,
  "message" TEXT,
  "observed_at_micros" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_build_logs_legacy_id CHECK (tombstone OR "legacy_id" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_build_id CHECK (tombstone OR "build_id" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_machine_id CHECK (tombstone OR "machine_id" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_workload_id CHECK (tombstone OR "workload_id" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_log_type CHECK (tombstone OR "log_type" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_message CHECK (tombstone OR "message" IS NOT NULL),
  CONSTRAINT ck_live_build_logs_observed_at_micros CHECK (tombstone OR "observed_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_audit."audit_events" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "stream_id" TEXT,
  "sequence" BIGINT,
  "actor" TEXT,
  "action" TEXT,
  "target" TEXT,
  "decision" TEXT,
  "policy_version" BIGINT,
  "trace_id" TEXT,
  "occurred_at_micros" BIGINT,
  "details" BYTEA,
  "previous_event_integrity" BYTEA,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_audit_events_stream_id CHECK (tombstone OR "stream_id" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_sequence CHECK (tombstone OR "sequence" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_actor CHECK (tombstone OR "actor" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_action CHECK (tombstone OR "action" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_target CHECK (tombstone OR "target" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_decision CHECK (tombstone OR "decision" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_policy_version CHECK (tombstone OR "policy_version" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_trace_id CHECK (tombstone OR "trace_id" IS NOT NULL),
  CONSTRAINT ck_live_audit_events_occurred_at_micros CHECK (tombstone OR "occurred_at_micros" IS NOT NULL),
  CONSTRAINT ck_append_envelope CHECK (revision = 1 AND previous_integrity IS NULL AND NOT tombstone)
);

CREATE TABLE IF NOT EXISTS aseman_finance."wallets" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "currency" TEXT,
  "balance_minor" BIGINT,
  "scale" BIGINT,
  "state" TEXT,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_wallets_currency CHECK (tombstone OR "currency" IS NOT NULL),
  CONSTRAINT ck_live_wallets_balance_minor CHECK (tombstone OR "balance_minor" IS NOT NULL),
  CONSTRAINT ck_live_wallets_scale CHECK (tombstone OR "scale" IS NOT NULL),
  CONSTRAINT ck_live_wallets_state CHECK (tombstone OR "state" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_finance."ledger_entries" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "entry_group_id" UUID,
  "sequence" BIGINT,
  "amount_minor" BIGINT,
  "currency" TEXT,
  "scale" BIGINT,
  "direction" TEXT,
  "idempotency_key" TEXT,
  "occurred_at_micros" BIGINT,
  "wallet" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_ledger_entries_entry_group_id CHECK (tombstone OR "entry_group_id" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_sequence CHECK (tombstone OR "sequence" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_amount_minor CHECK (tombstone OR "amount_minor" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_currency CHECK (tombstone OR "currency" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_scale CHECK (tombstone OR "scale" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_direction CHECK (tombstone OR "direction" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_idempotency_key CHECK (tombstone OR "idempotency_key" IS NOT NULL),
  CONSTRAINT ck_live_ledger_entries_occurred_at_micros CHECK (tombstone OR "occurred_at_micros" IS NOT NULL),
  CONSTRAINT ck_append_envelope CHECK (revision = 1 AND previous_integrity IS NULL AND NOT tombstone)
);

CREATE TABLE IF NOT EXISTS aseman_finance."pricing_policies" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "version" BIGINT,
  "currency" TEXT,
  "scale" BIGINT,
  "rules" BYTEA,
  "effective_at_micros" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_pricing_policies_version CHECK (tombstone OR "version" IS NOT NULL),
  CONSTRAINT ck_live_pricing_policies_currency CHECK (tombstone OR "currency" IS NOT NULL),
  CONSTRAINT ck_live_pricing_policies_scale CHECK (tombstone OR "scale" IS NOT NULL),
  CONSTRAINT ck_live_pricing_policies_rules CHECK (tombstone OR "rules" IS NOT NULL),
  CONSTRAINT ck_live_pricing_policies_effective_at_micros CHECK (tombstone OR "effective_at_micros" IS NOT NULL),
  CONSTRAINT ck_append_envelope CHECK (revision = 1 AND previous_integrity IS NULL AND NOT tombstone)
);

CREATE TABLE IF NOT EXISTS aseman_finance."usage_records" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "metric" TEXT,
  "quantity" BIGINT,
  "interval_start_micros" BIGINT,
  "interval_end_micros" BIGINT,
  "idempotency_key" TEXT,
  "workload" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_usage_records_metric CHECK (tombstone OR "metric" IS NOT NULL),
  CONSTRAINT ck_live_usage_records_quantity CHECK (tombstone OR "quantity" IS NOT NULL),
  CONSTRAINT ck_live_usage_records_interval_start_micros CHECK (tombstone OR "interval_start_micros" IS NOT NULL),
  CONSTRAINT ck_live_usage_records_interval_end_micros CHECK (tombstone OR "interval_end_micros" IS NOT NULL),
  CONSTRAINT ck_live_usage_records_idempotency_key CHECK (tombstone OR "idempotency_key" IS NOT NULL),
  CONSTRAINT ck_append_envelope CHECK (revision = 1 AND previous_integrity IS NULL AND NOT tombstone)
);

CREATE TABLE IF NOT EXISTS aseman_outbox."messages" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "topic" TEXT,
  "aggregate_kind" TEXT,
  "aggregate_id" UUID,
  "event_type" TEXT,
  "payload" BYTEA,
  "idempotency_key" TEXT,
  "state" TEXT,
  "available_at_micros" BIGINT,
  "lease_owner" TEXT,
  "lease_until_micros" BIGINT,
  "attempts" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_messages_topic CHECK (tombstone OR "topic" IS NOT NULL),
  CONSTRAINT ck_live_messages_aggregate_kind CHECK (tombstone OR "aggregate_kind" IS NOT NULL),
  CONSTRAINT ck_live_messages_aggregate_id CHECK (tombstone OR "aggregate_id" IS NOT NULL),
  CONSTRAINT ck_live_messages_event_type CHECK (tombstone OR "event_type" IS NOT NULL),
  CONSTRAINT ck_live_messages_payload CHECK (tombstone OR "payload" IS NOT NULL),
  CONSTRAINT ck_live_messages_idempotency_key CHECK (tombstone OR "idempotency_key" IS NOT NULL),
  CONSTRAINT ck_live_messages_state CHECK (tombstone OR "state" IS NOT NULL),
  CONSTRAINT ck_live_messages_available_at_micros CHECK (tombstone OR "available_at_micros" IS NOT NULL),
  CONSTRAINT ck_live_messages_attempts CHECK (tombstone OR "attempts" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_realtime."events" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "stream_id" TEXT,
  "sequence" BIGINT,
  "event_type" TEXT,
  "authorization_scope" BYTEA,
  "producer" TEXT,
  "trace_id" TEXT,
  "correlation_id" TEXT,
  "payload" BYTEA,
  "payload_digest" BYTEA,
  "retention_class" TEXT,
  "idempotency_key" TEXT,
  "occurred_at_micros" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_events_stream_id CHECK (tombstone OR "stream_id" IS NOT NULL),
  CONSTRAINT ck_live_events_sequence CHECK (tombstone OR "sequence" IS NOT NULL),
  CONSTRAINT ck_live_events_event_type CHECK (tombstone OR "event_type" IS NOT NULL),
  CONSTRAINT ck_live_events_authorization_scope CHECK (tombstone OR "authorization_scope" IS NOT NULL),
  CONSTRAINT ck_live_events_producer CHECK (tombstone OR "producer" IS NOT NULL),
  CONSTRAINT ck_live_events_trace_id CHECK (tombstone OR "trace_id" IS NOT NULL),
  CONSTRAINT ck_live_events_payload CHECK (tombstone OR "payload" IS NOT NULL),
  CONSTRAINT ck_live_events_payload_digest CHECK (tombstone OR "payload_digest" IS NOT NULL),
  CONSTRAINT ck_live_events_retention_class CHECK (tombstone OR "retention_class" IS NOT NULL),
  CONSTRAINT ck_live_events_occurred_at_micros CHECK (tombstone OR "occurred_at_micros" IS NOT NULL),
  CONSTRAINT ck_append_envelope CHECK (revision = 1 AND previous_integrity IS NULL AND NOT tombstone)
);

CREATE TABLE IF NOT EXISTS aseman_realtime."subscriptions" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "subscriber_id" TEXT,
  "stream_pattern" TEXT,
  "authorization_scope" BYTEA,
  "state" TEXT,
  "body_created_at_micros" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_subscriptions_subscriber_id CHECK (tombstone OR "subscriber_id" IS NOT NULL),
  CONSTRAINT ck_live_subscriptions_stream_pattern CHECK (tombstone OR "stream_pattern" IS NOT NULL),
  CONSTRAINT ck_live_subscriptions_authorization_scope CHECK (tombstone OR "authorization_scope" IS NOT NULL),
  CONSTRAINT ck_live_subscriptions_state CHECK (tombstone OR "state" IS NOT NULL),
  CONSTRAINT ck_live_subscriptions_created_at_micros CHECK (tombstone OR "body_created_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_realtime."consumer_offsets" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "consumer_id" TEXT,
  "stream_id" TEXT,
  "last_sequence" BIGINT,
  "checkpoint_digest" BYTEA,
  "checkpointed_at_micros" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_consumer_offsets_consumer_id CHECK (tombstone OR "consumer_id" IS NOT NULL),
  CONSTRAINT ck_live_consumer_offsets_stream_id CHECK (tombstone OR "stream_id" IS NOT NULL),
  CONSTRAINT ck_live_consumer_offsets_last_sequence CHECK (tombstone OR "last_sequence" IS NOT NULL),
  CONSTRAINT ck_live_consumer_offsets_checkpoint_digest CHECK (tombstone OR "checkpoint_digest" IS NOT NULL),
  CONSTRAINT ck_live_consumer_offsets_checkpointed_at_micros CHECK (tombstone OR "checkpointed_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_realtime."dead_letters" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "consumer_id" TEXT,
  "attempts" BIGINT,
  "reason" TEXT,
  "payload_digest" BYTEA,
  "failed_at_micros" BIGINT,
  "resolution" TEXT,
  "event" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_dead_letters_consumer_id CHECK (tombstone OR "consumer_id" IS NOT NULL),
  CONSTRAINT ck_live_dead_letters_attempts CHECK (tombstone OR "attempts" IS NOT NULL),
  CONSTRAINT ck_live_dead_letters_reason CHECK (tombstone OR "reason" IS NOT NULL),
  CONSTRAINT ck_live_dead_letters_payload_digest CHECK (tombstone OR "payload_digest" IS NOT NULL),
  CONSTRAINT ck_live_dead_letters_failed_at_micros CHECK (tombstone OR "failed_at_micros" IS NOT NULL)
);

ALTER TABLE aseman_telemetry."workload_samples" DROP CONSTRAINT IF EXISTS fk_workload_samples_workload;
ALTER TABLE aseman_telemetry."workload_samples" ADD CONSTRAINT fk_workload_samples_workload FOREIGN KEY ("workload") REFERENCES aseman_core."workloads"(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_workload_samples_observed_at_micros ON aseman_telemetry."workload_samples" ("observed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_workload_samples_observed_at_micros ON aseman_telemetry."workload_samples" USING BRIN ("observed_at_micros");
CREATE INDEX IF NOT EXISTS ix_workload_samples_metric_observed_at_micros ON aseman_telemetry."workload_samples" ("metric", "observed_at_micros", id) WHERE NOT tombstone;

ALTER TABLE aseman_telemetry."node_health_samples" DROP CONSTRAINT IF EXISTS fk_node_health_samples_node;
ALTER TABLE aseman_telemetry."node_health_samples" ADD CONSTRAINT fk_node_health_samples_node FOREIGN KEY ("node") REFERENCES aseman_core."nodes"(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_node_health_samples_observed_at_micros ON aseman_telemetry."node_health_samples" ("observed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_node_health_samples_observed_at_micros ON aseman_telemetry."node_health_samples" USING BRIN ("observed_at_micros");

CREATE INDEX IF NOT EXISTS ix_build_logs_build_id_observed_at_micros ON aseman_telemetry."build_logs" ("build_id", "observed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_build_logs_workload_id_observed_at_micros ON aseman_telemetry."build_logs" ("workload_id", "observed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_build_logs_observed_at_micros ON aseman_telemetry."build_logs" ("observed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_build_logs_observed_at_micros ON aseman_telemetry."build_logs" USING BRIN ("observed_at_micros");

CREATE UNIQUE INDEX IF NOT EXISTS uq_audit_events_stream_id_sequence ON aseman_audit."audit_events" ("stream_id", "sequence") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_audit_events_occurred_at_micros ON aseman_audit."audit_events" ("occurred_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_audit_events_occurred_at_micros ON aseman_audit."audit_events" USING BRIN ("occurred_at_micros");
CREATE INDEX IF NOT EXISTS ix_audit_events_trace_id_occurred_at_micros ON aseman_audit."audit_events" ("trace_id", "occurred_at_micros", id) WHERE NOT tombstone;
DROP TRIGGER IF EXISTS trg_immutable_audit_events ON aseman_audit."audit_events";
CREATE TRIGGER trg_immutable_audit_events BEFORE UPDATE OR DELETE ON aseman_audit."audit_events" FOR EACH ROW EXECUTE FUNCTION aseman_storage.reject_capsule_mutation();

ALTER TABLE aseman_finance."wallets" DROP CONSTRAINT IF EXISTS fk_wallets_creature;
ALTER TABLE aseman_finance."wallets" ADD CONSTRAINT fk_wallets_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_wallets_creature_currency ON aseman_finance."wallets" ("creature", "currency") WHERE NOT tombstone;

ALTER TABLE aseman_finance."ledger_entries" DROP CONSTRAINT IF EXISTS fk_ledger_entries_wallet;
ALTER TABLE aseman_finance."ledger_entries" ADD CONSTRAINT fk_ledger_entries_wallet FOREIGN KEY ("wallet") REFERENCES aseman_finance."wallets"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_ledger_entries_idempotency_key ON aseman_finance."ledger_entries" ("idempotency_key") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_ledger_entries_entry_group_id_sequence ON aseman_finance."ledger_entries" ("entry_group_id", "sequence") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_ledger_entries_occurred_at_micros ON aseman_finance."ledger_entries" ("occurred_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_ledger_entries_occurred_at_micros ON aseman_finance."ledger_entries" USING BRIN ("occurred_at_micros");
DROP TRIGGER IF EXISTS trg_immutable_ledger_entries ON aseman_finance."ledger_entries";
CREATE TRIGGER trg_immutable_ledger_entries BEFORE UPDATE OR DELETE ON aseman_finance."ledger_entries" FOR EACH ROW EXECUTE FUNCTION aseman_storage.reject_capsule_mutation();

CREATE UNIQUE INDEX IF NOT EXISTS uq_pricing_policies_version ON aseman_finance."pricing_policies" ("version") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_pricing_policies_effective_at_micros ON aseman_finance."pricing_policies" ("effective_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_pricing_policies_effective_at_micros ON aseman_finance."pricing_policies" USING BRIN ("effective_at_micros");
DROP TRIGGER IF EXISTS trg_immutable_pricing_policies ON aseman_finance."pricing_policies";
CREATE TRIGGER trg_immutable_pricing_policies BEFORE UPDATE OR DELETE ON aseman_finance."pricing_policies" FOR EACH ROW EXECUTE FUNCTION aseman_storage.reject_capsule_mutation();

ALTER TABLE aseman_finance."usage_records" DROP CONSTRAINT IF EXISTS fk_usage_records_workload;
ALTER TABLE aseman_finance."usage_records" ADD CONSTRAINT fk_usage_records_workload FOREIGN KEY ("workload") REFERENCES aseman_core."workloads"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_usage_records_idempotency_key ON aseman_finance."usage_records" ("idempotency_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_usage_records_interval_start_micros_interval_end_micros ON aseman_finance."usage_records" ("interval_start_micros", "interval_end_micros", id) WHERE NOT tombstone;
DROP TRIGGER IF EXISTS trg_immutable_usage_records ON aseman_finance."usage_records";
CREATE TRIGGER trg_immutable_usage_records BEFORE UPDATE OR DELETE ON aseman_finance."usage_records" FOR EACH ROW EXECUTE FUNCTION aseman_storage.reject_capsule_mutation();

CREATE UNIQUE INDEX IF NOT EXISTS uq_messages_idempotency_key ON aseman_outbox."messages" ("idempotency_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_messages_state_available_at_micros ON aseman_outbox."messages" ("state", "available_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_messages_lease_until_micros ON aseman_outbox."messages" ("lease_until_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_messages_lease_until_micros ON aseman_outbox."messages" USING BRIN ("lease_until_micros");

CREATE UNIQUE INDEX IF NOT EXISTS uq_events_stream_id_sequence ON aseman_realtime."events" ("stream_id", "sequence") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_events_idempotency_key ON aseman_realtime."events" ("idempotency_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_events_stream_id_sequence ON aseman_realtime."events" ("stream_id", "sequence", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_events_occurred_at_micros ON aseman_realtime."events" ("occurred_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_events_occurred_at_micros ON aseman_realtime."events" USING BRIN ("occurred_at_micros");
DROP TRIGGER IF EXISTS trg_immutable_events ON aseman_realtime."events";
CREATE TRIGGER trg_immutable_events BEFORE UPDATE OR DELETE ON aseman_realtime."events" FOR EACH ROW EXECUTE FUNCTION aseman_storage.reject_capsule_mutation();

CREATE UNIQUE INDEX IF NOT EXISTS uq_subscriptions_subscriber_id_stream_pattern ON aseman_realtime."subscriptions" ("subscriber_id", "stream_pattern") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_subscriptions_created_at_micros ON aseman_realtime."subscriptions" ("body_created_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_subscriptions_created_at_micros ON aseman_realtime."subscriptions" USING BRIN ("body_created_at_micros");

CREATE UNIQUE INDEX IF NOT EXISTS uq_consumer_offsets_consumer_id_stream_id ON aseman_realtime."consumer_offsets" ("consumer_id", "stream_id") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_consumer_offsets_checkpointed_at_micros ON aseman_realtime."consumer_offsets" ("checkpointed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_consumer_offsets_checkpointed_at_micros ON aseman_realtime."consumer_offsets" USING BRIN ("checkpointed_at_micros");

ALTER TABLE aseman_realtime."dead_letters" DROP CONSTRAINT IF EXISTS fk_dead_letters_event;
ALTER TABLE aseman_realtime."dead_letters" ADD CONSTRAINT fk_dead_letters_event FOREIGN KEY ("event") REFERENCES aseman_realtime."events"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_dead_letters_event_consumer_id ON aseman_realtime."dead_letters" ("event", "consumer_id") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_dead_letters_failed_at_micros ON aseman_realtime."dead_letters" ("failed_at_micros", id) WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS brin_dead_letters_failed_at_micros ON aseman_realtime."dead_letters" USING BRIN ("failed_at_micros");

COMMIT;
