-- Generated by scripts/generate_postgres_core.py; do not edit by hand.
BEGIN;
CREATE SCHEMA IF NOT EXISTS aseman_core;
REVOKE ALL ON SCHEMA aseman_core FROM PUBLIC;

CREATE TABLE IF NOT EXISTS aseman_core."users" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "username" TEXT,
  "email" TEXT,
  "public_key" BYTEA,
  "status" TEXT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_users_username CHECK (tombstone OR "username" IS NOT NULL),
  CONSTRAINT ck_live_users_public_key CHECK (tombstone OR "public_key" IS NOT NULL),
  CONSTRAINT ck_live_users_status CHECK (tombstone OR "status" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."creatures" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "username" TEXT,
  "creature_type" TEXT,
  "public_key" BYTEA,
  "status" TEXT,
  "chain_id" TEXT,
  "subchain_id" TEXT,
  "owner" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_creatures_username CHECK (tombstone OR "username" IS NOT NULL),
  CONSTRAINT ck_live_creatures_creature_type CHECK (tombstone OR "creature_type" IS NOT NULL),
  CONSTRAINT ck_live_creatures_public_key CHECK (tombstone OR "public_key" IS NOT NULL),
  CONSTRAINT ck_live_creatures_status CHECK (tombstone OR "status" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."programs" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "machine_id" TEXT,
  "runtime" TEXT,
  "path" TEXT,
  "comment" TEXT,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_programs_machine_id CHECK (tombstone OR "machine_id" IS NOT NULL),
  CONSTRAINT ck_live_programs_runtime CHECK (tombstone OR "runtime" IS NOT NULL),
  CONSTRAINT ck_live_programs_path CHECK (tombstone OR "path" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."stores" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "is_public" BOOLEAN,
  "member_count" BIGINT,
  "persistent_history" BOOLEAN,
  "signal_count" BIGINT,
  "tag" TEXT,
  "creature" UUID NOT NULL,
  "parent" UUID,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_stores_is_public CHECK (tombstone OR "is_public" IS NOT NULL),
  CONSTRAINT ck_live_stores_member_count CHECK (tombstone OR "member_count" IS NOT NULL),
  CONSTRAINT ck_live_stores_persistent_history CHECK (tombstone OR "persistent_history" IS NOT NULL),
  CONSTRAINT ck_live_stores_signal_count CHECK (tombstone OR "signal_count" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."store_memberships" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "member_kind" TEXT,
  "member_ref" TEXT,
  "permissions" TEXT,
  "joined_at_micros" BIGINT,
  "store" UUID NOT NULL,
  "creature" UUID,
  "program" UUID,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_store_memberships_member_kind CHECK (tombstone OR "member_kind" IS NOT NULL),
  CONSTRAINT ck_live_store_memberships_member_ref CHECK (tombstone OR "member_ref" IS NOT NULL),
  CONSTRAINT ck_live_store_memberships_permissions CHECK (tombstone OR "permissions" IS NOT NULL),
  CONSTRAINT ck_live_store_memberships_joined_at_micros CHECK (tombstone OR "joined_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."access_levels" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "level" TEXT,
  "permissions" BYTEA,
  "store" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_access_levels_level CHECK (tombstone OR "level" IS NOT NULL),
  CONSTRAINT ck_live_access_levels_permissions CHECK (tombstone OR "permissions" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."capability_grants" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "subject_kind" TEXT,
  "subject_id" UUID,
  "issuer_kind" TEXT,
  "issuer_id" UUID,
  "resource_kind" TEXT,
  "resource_id" TEXT,
  "max_depth" BIGINT,
  "parent_id" UUID,
  "not_before_micros" BIGINT,
  "expires_at_micros" BIGINT,
  "revoked_at_micros" BIGINT,
  "policy_version" TEXT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_capability_grants_subject_kind CHECK (tombstone OR "subject_kind" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_subject_id CHECK (tombstone OR "subject_id" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_issuer_kind CHECK (tombstone OR "issuer_kind" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_issuer_id CHECK (tombstone OR "issuer_id" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_resource_kind CHECK (tombstone OR "resource_kind" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_max_depth CHECK (tombstone OR "max_depth" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_not_before_micros CHECK (tombstone OR "not_before_micros" IS NOT NULL),
  CONSTRAINT ck_live_capability_grants_policy_version CHECK (tombstone OR "policy_version" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."sessions" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "token_digest" BYTEA,
  "issued_at_micros" BIGINT,
  "expires_at_micros" BIGINT,
  "revoked_at_micros" BIGINT,
  "user" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_sessions_token_digest CHECK (tombstone OR "token_digest" IS NOT NULL),
  CONSTRAINT ck_live_sessions_issued_at_micros CHECK (tombstone OR "issued_at_micros" IS NOT NULL),
  CONSTRAINT ck_live_sessions_expires_at_micros CHECK (tombstone OR "expires_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."files" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "store_key" TEXT,
  "content_digest" BYTEA,
  "media_type" TEXT,
  "size_bytes" BIGINT,
  "owner" UUID NOT NULL,
  "store" UUID,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_files_store_key CHECK (tombstone OR "store_key" IS NOT NULL),
  CONSTRAINT ck_live_files_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL),
  CONSTRAINT ck_live_files_size_bytes CHECK (tombstone OR "size_bytes" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."workloads" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "workload_name" TEXT,
  "runtime" TEXT,
  "desired_state" TEXT,
  "desired_generation" BIGINT,
  "observed_state" TEXT,
  "observed_generation" BIGINT,
  "program" UUID NOT NULL,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_workloads_workload_name CHECK (tombstone OR "workload_name" IS NOT NULL),
  CONSTRAINT ck_live_workloads_runtime CHECK (tombstone OR "runtime" IS NOT NULL),
  CONSTRAINT ck_live_workloads_desired_state CHECK (tombstone OR "desired_state" IS NOT NULL),
  CONSTRAINT ck_live_workloads_desired_generation CHECK (tombstone OR "desired_generation" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."workload_operations" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "operation" TEXT,
  "idempotency_key" TEXT,
  "state" TEXT,
  "requested_at_micros" BIGINT,
  "completed_at_micros" BIGINT,
  "workload" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_workload_operations_operation CHECK (tombstone OR "operation" IS NOT NULL),
  CONSTRAINT ck_live_workload_operations_idempotency_key CHECK (tombstone OR "idempotency_key" IS NOT NULL),
  CONSTRAINT ck_live_workload_operations_state CHECK (tombstone OR "state" IS NOT NULL),
  CONSTRAINT ck_live_workload_operations_requested_at_micros CHECK (tombstone OR "requested_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."nodes" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "name" TEXT,
  "region" TEXT,
  "status" TEXT,
  "descriptor_digest" BYTEA,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_nodes_name CHECK (tombstone OR "name" IS NOT NULL),
  CONSTRAINT ck_live_nodes_status CHECK (tombstone OR "status" IS NOT NULL),
  CONSTRAINT ck_live_nodes_descriptor_digest CHECK (tombstone OR "descriptor_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."federation_peers" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "origin" TEXT,
  "endpoint" TEXT,
  "trust_state" TEXT,
  "descriptor_digest" BYTEA,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_federation_peers_origin CHECK (tombstone OR "origin" IS NOT NULL),
  CONSTRAINT ck_live_federation_peers_endpoint CHECK (tombstone OR "endpoint" IS NOT NULL),
  CONSTRAINT ck_live_federation_peers_trust_state CHECK (tombstone OR "trust_state" IS NOT NULL),
  CONSTRAINT ck_live_federation_peers_descriptor_digest CHECK (tombstone OR "descriptor_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."identity_keys" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "subject_kind" TEXT,
  "subject_id" UUID,
  "purpose" TEXT,
  "epoch" BIGINT,
  "key_id" TEXT,
  "public_key" BYTEA,
  "not_before_micros" BIGINT,
  "expires_at_micros" BIGINT,
  "retired_at_micros" BIGINT,
  "revoked_at_micros" BIGINT,
  "legacy" BOOLEAN,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_identity_keys_subject_kind CHECK (tombstone OR "subject_kind" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_subject_id CHECK (tombstone OR "subject_id" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_purpose CHECK (tombstone OR "purpose" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_epoch CHECK (tombstone OR "epoch" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_key_id CHECK (tombstone OR "key_id" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_public_key CHECK (tombstone OR "public_key" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_not_before_micros CHECK (tombstone OR "not_before_micros" IS NOT NULL),
  CONSTRAINT ck_live_identity_keys_legacy CHECK (tombstone OR "legacy" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."module_installations" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "module_name" TEXT,
  "module_kind" TEXT,
  "version" TEXT,
  "artifact_digest" BYTEA,
  "state" TEXT,
  "routing_generation" BIGINT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_module_installations_module_name CHECK (tombstone OR "module_name" IS NOT NULL),
  CONSTRAINT ck_live_module_installations_module_kind CHECK (tombstone OR "module_kind" IS NOT NULL),
  CONSTRAINT ck_live_module_installations_version CHECK (tombstone OR "version" IS NOT NULL),
  CONSTRAINT ck_live_module_installations_artifact_digest CHECK (tombstone OR "artifact_digest" IS NOT NULL),
  CONSTRAINT ck_live_module_installations_state CHECK (tombstone OR "state" IS NOT NULL),
  CONSTRAINT ck_live_module_installations_routing_generation CHECK (tombstone OR "routing_generation" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."guest_database_bindings" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "provider_id" TEXT,
  "database_name" TEXT,
  "role_name" TEXT,
  "generation" BIGINT,
  "schema_catalog_revision" BIGINT,
  "status" TEXT,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_guest_database_bindings_provider_id CHECK (tombstone OR "provider_id" IS NOT NULL),
  CONSTRAINT ck_live_guest_database_bindings_database_name CHECK (tombstone OR "database_name" IS NOT NULL),
  CONSTRAINT ck_live_guest_database_bindings_role_name CHECK (tombstone OR "role_name" IS NOT NULL),
  CONSTRAINT ck_live_guest_database_bindings_generation CHECK (tombstone OR "generation" IS NOT NULL),
  CONSTRAINT ck_live_guest_database_bindings_schema_catalog_revision CHECK (tombstone OR "schema_catalog_revision" IS NOT NULL),
  CONSTRAINT ck_live_guest_database_bindings_status CHECK (tombstone OR "status" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."guest_schema_definitions" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "schema_name" TEXT,
  "body_schema_version" BIGINT,
  "definition" BYTEA,
  "status" TEXT,
  "creature" UUID NOT NULL,
  "binding" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_guest_schema_definitions_schema_name CHECK (tombstone OR "schema_name" IS NOT NULL),
  CONSTRAINT ck_live_guest_schema_definitions_schema_version CHECK (tombstone OR "body_schema_version" IS NOT NULL),
  CONSTRAINT ck_live_guest_schema_definitions_definition CHECK (tombstone OR "definition" IS NOT NULL),
  CONSTRAINT ck_live_guest_schema_definitions_status CHECK (tombstone OR "status" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."chains" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "store_id" TEXT,
  "status" TEXT,
  "store" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_chains_store_id CHECK (tombstone OR "store_id" IS NOT NULL),
  CONSTRAINT ck_live_chains_status CHECK (tombstone OR "status" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."chain_shards" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "work_chain_id" TEXT,
  "shard_name" TEXT,
  "chain" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_chain_shards_work_chain_id CHECK (tombstone OR "work_chain_id" IS NOT NULL),
  CONSTRAINT ck_live_chain_shards_shard_name CHECK (tombstone OR "shard_name" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."entities" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "entity_name" TEXT,
  "entity_type" TEXT,
  "image_name" TEXT,
  "program" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_entities_entity_name CHECK (tombstone OR "entity_name" IS NOT NULL),
  CONSTRAINT ck_live_entities_entity_type CHECK (tombstone OR "entity_type" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."user_metadata_documents" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_user_metadata_documents_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_user_metadata_documents_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_user_metadata_documents_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."creature_metadata_documents" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_creature_metadata_documents_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_creature_metadata_documents_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_creature_metadata_documents_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."store_metadata_documents" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "store" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_store_metadata_documents_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_store_metadata_documents_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_store_metadata_documents_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."program_metadata_documents" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "program" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_program_metadata_documents_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_program_metadata_documents_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_program_metadata_documents_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."creature_types" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "type_name" TEXT,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_creature_types_type_name CHECK (tombstone OR "type_name" IS NOT NULL),
  CONSTRAINT ck_live_creature_types_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_creature_types_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_creature_types_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."gateway_routes" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "path" TEXT,
  "entity_name" TEXT,
  "runtime" TEXT,
  "creature" UUID NOT NULL,
  "program" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_gateway_routes_path CHECK (tombstone OR "path" IS NOT NULL),
  CONSTRAINT ck_live_gateway_routes_entity_name CHECK (tombstone OR "entity_name" IS NOT NULL),
  CONSTRAINT ck_live_gateway_routes_runtime CHECK (tombstone OR "runtime" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."program_alarms" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "fire_at_micros" BIGINT,
  "entity_name" TEXT,
  "data" TEXT,
  "program" UUID NOT NULL,
  "store" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_program_alarms_fire_at_micros CHECK (tombstone OR "fire_at_micros" IS NOT NULL),
  CONSTRAINT ck_live_program_alarms_entity_name CHECK (tombstone OR "entity_name" IS NOT NULL),
  CONSTRAINT ck_live_program_alarms_data CHECK (tombstone OR "data" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."vm_resource_stores" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "name" TEXT,
  "machine_ref" TEXT,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_vm_resource_stores_name CHECK (tombstone OR "name" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_stores_machine_ref CHECK (tombstone OR "machine_ref" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_stores_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_stores_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_stores_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."vm_resource_entities" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "entity_type" TEXT,
  "entity_ref" TEXT,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "artifact_present" BOOLEAN,
  "store_key" TEXT,
  "artifact_digest" BYTEA,
  "size_bytes" BIGINT,
  "media_type" TEXT,
  "resource_store" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_vm_resource_entities_entity_type CHECK (tombstone OR "entity_type" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_entities_entity_ref CHECK (tombstone OR "entity_ref" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_entities_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_entities_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_entities_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL),
  CONSTRAINT ck_live_vm_resource_entities_artifact_present CHECK (tombstone OR "artifact_present" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."entity_configs" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  "entity" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_entity_configs_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_entity_configs_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_entity_configs_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."entity_artifacts" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "artifact_role" TEXT,
  "artifact_present" BOOLEAN,
  "store_key" TEXT,
  "artifact_digest" BYTEA,
  "size_bytes" BIGINT,
  "media_type" TEXT,
  "entity" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_entity_artifacts_artifact_role CHECK (tombstone OR "artifact_role" IS NOT NULL),
  CONSTRAINT ck_live_entity_artifacts_artifact_present CHECK (tombstone OR "artifact_present" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."creature_secrets" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "name" TEXT,
  "algorithm" TEXT,
  "ciphertext" BYTEA,
  "key_fingerprint" BYTEA,
  "creature" UUID NOT NULL,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_creature_secrets_name CHECK (tombstone OR "name" IS NOT NULL),
  CONSTRAINT ck_live_creature_secrets_algorithm CHECK (tombstone OR "algorithm" IS NOT NULL),
  CONSTRAINT ck_live_creature_secrets_ciphertext CHECK (tombstone OR "ciphertext" IS NOT NULL),
  CONSTRAINT ck_live_creature_secrets_key_fingerprint CHECK (tombstone OR "key_fingerprint" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."secret_grants" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "grantee_ref" TEXT,
  "expires_at_micros" BIGINT,
  "secret" UUID NOT NULL,
  "grantee" UUID,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_secret_grants_grantee_ref CHECK (tombstone OR "grantee_ref" IS NOT NULL),
  CONSTRAINT ck_live_secret_grants_expires_at_micros CHECK (tombstone OR "expires_at_micros" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."bridge_grants" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "token_digest" BYTEA,
  "minted_by_ref" TEXT,
  "expires_at_micros" BIGINT,
  "document_path" TEXT,
  "entry_count" BIGINT,
  "content_digest" BYTEA,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_bridge_grants_token_digest CHECK (tombstone OR "token_digest" IS NOT NULL),
  CONSTRAINT ck_live_bridge_grants_minted_by_ref CHECK (tombstone OR "minted_by_ref" IS NOT NULL),
  CONSTRAINT ck_live_bridge_grants_expires_at_micros CHECK (tombstone OR "expires_at_micros" IS NOT NULL),
  CONSTRAINT ck_live_bridge_grants_document_path CHECK (tombstone OR "document_path" IS NOT NULL),
  CONSTRAINT ck_live_bridge_grants_entry_count CHECK (tombstone OR "entry_count" IS NOT NULL),
  CONSTRAINT ck_live_bridge_grants_content_digest CHECK (tombstone OR "content_digest" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."bridge_topics" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "topic" TEXT,
  "owner_ref" TEXT,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_bridge_topics_topic CHECK (tombstone OR "topic" IS NOT NULL),
  CONSTRAINT ck_live_bridge_topics_owner_ref CHECK (tombstone OR "owner_ref" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS aseman_core."legacy_identities" (
  id UUID PRIMARY KEY,
  schema_version INTEGER NOT NULL CHECK (schema_version > 0),
  revision BIGINT NOT NULL CHECK (revision > 0),
  created_at_micros BIGINT NOT NULL,
  updated_at_micros BIGINT NOT NULL CHECK (updated_at_micros >= created_at_micros),
  previous_integrity BYTEA,
  integrity_hash BYTEA NOT NULL CHECK (octet_length(integrity_hash) = 32),
  owner_type TEXT NOT NULL,
  owner_id UUID,
  owner_name TEXT,
  tombstone BOOLEAN NOT NULL DEFAULT FALSE,
  capsule_cbor BYTEA NOT NULL,
  "family" TEXT,
  "legacy_id" TEXT,
  "target_kind" TEXT,
  "target_id" UUID,
  CONSTRAINT ck_revision_chain CHECK ((revision = 1) = (previous_integrity IS NULL)),
  CONSTRAINT ck_previous_integrity CHECK (previous_integrity IS NULL OR octet_length(previous_integrity) = 32),
  CONSTRAINT ck_owner_scope CHECK ((owner_type = 'global' AND owner_id IS NULL AND owner_name IS NULL) OR (owner_type IN ('node', 'creature') AND owner_id IS NOT NULL AND owner_name IS NULL) OR (owner_type = 'module' AND owner_id IS NULL AND owner_name IS NOT NULL)),
  CONSTRAINT ck_live_legacy_identities_family CHECK (tombstone OR "family" IS NOT NULL),
  CONSTRAINT ck_live_legacy_identities_legacy_id CHECK (tombstone OR "legacy_id" IS NOT NULL),
  CONSTRAINT ck_live_legacy_identities_target_kind CHECK (tombstone OR "target_kind" IS NOT NULL),
  CONSTRAINT ck_live_legacy_identities_target_id CHECK (tombstone OR "target_id" IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON aseman_core."users" ("username") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON aseman_core."users" ("email") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_public_key ON aseman_core."users" ("public_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_users_updated_at ON aseman_core."users" (updated_at_micros, id);

ALTER TABLE aseman_core."creatures" DROP CONSTRAINT IF EXISTS fk_creatures_owner;
ALTER TABLE aseman_core."creatures" ADD CONSTRAINT fk_creatures_owner FOREIGN KEY ("owner") REFERENCES aseman_core."users"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_creatures_username ON aseman_core."creatures" ("username") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_creatures_public_key ON aseman_core."creatures" ("public_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_creatures_updated_at ON aseman_core."creatures" (updated_at_micros, id);

ALTER TABLE aseman_core."programs" DROP CONSTRAINT IF EXISTS fk_programs_creature;
ALTER TABLE aseman_core."programs" ADD CONSTRAINT fk_programs_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_programs_updated_at ON aseman_core."programs" (updated_at_micros, id);

ALTER TABLE aseman_core."stores" DROP CONSTRAINT IF EXISTS fk_stores_creature;
ALTER TABLE aseman_core."stores" ADD CONSTRAINT fk_stores_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE RESTRICT;
ALTER TABLE aseman_core."stores" DROP CONSTRAINT IF EXISTS fk_stores_parent;
ALTER TABLE aseman_core."stores" ADD CONSTRAINT fk_stores_parent FOREIGN KEY ("parent") REFERENCES aseman_core."stores"(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS ix_stores_updated_at ON aseman_core."stores" (updated_at_micros, id);

ALTER TABLE aseman_core."store_memberships" DROP CONSTRAINT IF EXISTS fk_store_memberships_store;
ALTER TABLE aseman_core."store_memberships" ADD CONSTRAINT fk_store_memberships_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."store_memberships" DROP CONSTRAINT IF EXISTS fk_store_memberships_creature;
ALTER TABLE aseman_core."store_memberships" ADD CONSTRAINT fk_store_memberships_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."store_memberships" DROP CONSTRAINT IF EXISTS fk_store_memberships_program;
ALTER TABLE aseman_core."store_memberships" ADD CONSTRAINT fk_store_memberships_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_store_memberships_store_member_kind_member_ref ON aseman_core."store_memberships" ("store", "member_kind", "member_ref") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_store_memberships_updated_at ON aseman_core."store_memberships" (updated_at_micros, id);

ALTER TABLE aseman_core."access_levels" DROP CONSTRAINT IF EXISTS fk_access_levels_store;
ALTER TABLE aseman_core."access_levels" ADD CONSTRAINT fk_access_levels_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_access_levels_store_level ON aseman_core."access_levels" ("store", "level") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_access_levels_updated_at ON aseman_core."access_levels" (updated_at_micros, id);

CREATE INDEX IF NOT EXISTS ix_capability_grants_updated_at ON aseman_core."capability_grants" (updated_at_micros, id);

ALTER TABLE aseman_core."sessions" DROP CONSTRAINT IF EXISTS fk_sessions_user;
ALTER TABLE aseman_core."sessions" ADD CONSTRAINT fk_sessions_user FOREIGN KEY ("user") REFERENCES aseman_core."users"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_sessions_token_digest ON aseman_core."sessions" ("token_digest") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_sessions_updated_at ON aseman_core."sessions" (updated_at_micros, id);

ALTER TABLE aseman_core."files" DROP CONSTRAINT IF EXISTS fk_files_owner;
ALTER TABLE aseman_core."files" ADD CONSTRAINT fk_files_owner FOREIGN KEY ("owner") REFERENCES aseman_core."users"(id) ON DELETE RESTRICT;
ALTER TABLE aseman_core."files" DROP CONSTRAINT IF EXISTS fk_files_store;
ALTER TABLE aseman_core."files" ADD CONSTRAINT fk_files_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_files_store_key ON aseman_core."files" ("store_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_files_updated_at ON aseman_core."files" (updated_at_micros, id);

ALTER TABLE aseman_core."workloads" DROP CONSTRAINT IF EXISTS fk_workloads_program;
ALTER TABLE aseman_core."workloads" ADD CONSTRAINT fk_workloads_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE RESTRICT;
ALTER TABLE aseman_core."workloads" DROP CONSTRAINT IF EXISTS fk_workloads_creature;
ALTER TABLE aseman_core."workloads" ADD CONSTRAINT fk_workloads_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_workloads_program_workload_name ON aseman_core."workloads" ("program", "workload_name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_workloads_updated_at ON aseman_core."workloads" (updated_at_micros, id);

ALTER TABLE aseman_core."workload_operations" DROP CONSTRAINT IF EXISTS fk_workload_operations_workload;
ALTER TABLE aseman_core."workload_operations" ADD CONSTRAINT fk_workload_operations_workload FOREIGN KEY ("workload") REFERENCES aseman_core."workloads"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_workload_operations_idempotency_key ON aseman_core."workload_operations" ("idempotency_key") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_workload_operations_updated_at ON aseman_core."workload_operations" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_nodes_name ON aseman_core."nodes" ("name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_nodes_updated_at ON aseman_core."nodes" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_federation_peers_origin ON aseman_core."federation_peers" ("origin") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_federation_peers_updated_at ON aseman_core."federation_peers" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_keys_key_id ON aseman_core."identity_keys" ("key_id") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_keys_subject_kind_subject_id_purpose_epoch ON aseman_core."identity_keys" ("subject_kind", "subject_id", "purpose", "epoch") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_identity_keys_updated_at ON aseman_core."identity_keys" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_module_installations_module_name_version ON aseman_core."module_installations" ("module_name", "version") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_module_installations_updated_at ON aseman_core."module_installations" (updated_at_micros, id);

ALTER TABLE aseman_core."guest_database_bindings" DROP CONSTRAINT IF EXISTS fk_guest_database_bindings_creature;
ALTER TABLE aseman_core."guest_database_bindings" ADD CONSTRAINT fk_guest_database_bindings_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_database_bindings_creature ON aseman_core."guest_database_bindings" ("creature") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_database_bindings_provider_id_database_name ON aseman_core."guest_database_bindings" ("provider_id", "database_name") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_database_bindings_provider_id_role_name ON aseman_core."guest_database_bindings" ("provider_id", "role_name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_guest_database_bindings_updated_at ON aseman_core."guest_database_bindings" (updated_at_micros, id);

ALTER TABLE aseman_core."guest_schema_definitions" DROP CONSTRAINT IF EXISTS fk_guest_schema_definitions_creature;
ALTER TABLE aseman_core."guest_schema_definitions" ADD CONSTRAINT fk_guest_schema_definitions_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."guest_schema_definitions" DROP CONSTRAINT IF EXISTS fk_guest_schema_definitions_binding;
ALTER TABLE aseman_core."guest_schema_definitions" ADD CONSTRAINT fk_guest_schema_definitions_binding FOREIGN KEY ("binding") REFERENCES aseman_core."guest_database_bindings"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_schema_definitions_creature_schema_name_schema_version ON aseman_core."guest_schema_definitions" ("creature", "schema_name", "body_schema_version") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_guest_schema_definitions_updated_at ON aseman_core."guest_schema_definitions" (updated_at_micros, id);

ALTER TABLE aseman_core."chains" DROP CONSTRAINT IF EXISTS fk_chains_store;
ALTER TABLE aseman_core."chains" ADD CONSTRAINT fk_chains_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX IF NOT EXISTS uq_chains_store_id ON aseman_core."chains" ("store_id") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_chains_updated_at ON aseman_core."chains" (updated_at_micros, id);

ALTER TABLE aseman_core."chain_shards" DROP CONSTRAINT IF EXISTS fk_chain_shards_chain;
ALTER TABLE aseman_core."chain_shards" ADD CONSTRAINT fk_chain_shards_chain FOREIGN KEY ("chain") REFERENCES aseman_core."chains"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_chain_shards_work_chain_id_shard_name ON aseman_core."chain_shards" ("work_chain_id", "shard_name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_chain_shards_updated_at ON aseman_core."chain_shards" (updated_at_micros, id);

ALTER TABLE aseman_core."entities" DROP CONSTRAINT IF EXISTS fk_entities_program;
ALTER TABLE aseman_core."entities" ADD CONSTRAINT fk_entities_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_entities_program_entity_name ON aseman_core."entities" ("program", "entity_name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_entities_updated_at ON aseman_core."entities" (updated_at_micros, id);

ALTER TABLE aseman_core."user_metadata_documents" DROP CONSTRAINT IF EXISTS fk_user_metadata_documents_creature;
ALTER TABLE aseman_core."user_metadata_documents" ADD CONSTRAINT fk_user_metadata_documents_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_metadata_documents_creature ON aseman_core."user_metadata_documents" ("creature") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_user_metadata_documents_updated_at ON aseman_core."user_metadata_documents" (updated_at_micros, id);

ALTER TABLE aseman_core."creature_metadata_documents" DROP CONSTRAINT IF EXISTS fk_creature_metadata_documents_creature;
ALTER TABLE aseman_core."creature_metadata_documents" ADD CONSTRAINT fk_creature_metadata_documents_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_creature_metadata_documents_creature ON aseman_core."creature_metadata_documents" ("creature") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_creature_metadata_documents_updated_at ON aseman_core."creature_metadata_documents" (updated_at_micros, id);

ALTER TABLE aseman_core."store_metadata_documents" DROP CONSTRAINT IF EXISTS fk_store_metadata_documents_store;
ALTER TABLE aseman_core."store_metadata_documents" ADD CONSTRAINT fk_store_metadata_documents_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_store_metadata_documents_store ON aseman_core."store_metadata_documents" ("store") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_store_metadata_documents_updated_at ON aseman_core."store_metadata_documents" (updated_at_micros, id);

ALTER TABLE aseman_core."program_metadata_documents" DROP CONSTRAINT IF EXISTS fk_program_metadata_documents_program;
ALTER TABLE aseman_core."program_metadata_documents" ADD CONSTRAINT fk_program_metadata_documents_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_program_metadata_documents_program ON aseman_core."program_metadata_documents" ("program") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_program_metadata_documents_updated_at ON aseman_core."program_metadata_documents" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_creature_types_type_name ON aseman_core."creature_types" ("type_name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_creature_types_updated_at ON aseman_core."creature_types" (updated_at_micros, id);

ALTER TABLE aseman_core."gateway_routes" DROP CONSTRAINT IF EXISTS fk_gateway_routes_creature;
ALTER TABLE aseman_core."gateway_routes" ADD CONSTRAINT fk_gateway_routes_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."gateway_routes" DROP CONSTRAINT IF EXISTS fk_gateway_routes_program;
ALTER TABLE aseman_core."gateway_routes" ADD CONSTRAINT fk_gateway_routes_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_gateway_routes_creature_path ON aseman_core."gateway_routes" ("creature", "path") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_gateway_routes_updated_at ON aseman_core."gateway_routes" (updated_at_micros, id);

ALTER TABLE aseman_core."program_alarms" DROP CONSTRAINT IF EXISTS fk_program_alarms_program;
ALTER TABLE aseman_core."program_alarms" ADD CONSTRAINT fk_program_alarms_program FOREIGN KEY ("program") REFERENCES aseman_core."programs"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."program_alarms" DROP CONSTRAINT IF EXISTS fk_program_alarms_store;
ALTER TABLE aseman_core."program_alarms" ADD CONSTRAINT fk_program_alarms_store FOREIGN KEY ("store") REFERENCES aseman_core."stores"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_program_alarms_program ON aseman_core."program_alarms" ("program") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_program_alarms_updated_at ON aseman_core."program_alarms" (updated_at_micros, id);

ALTER TABLE aseman_core."vm_resource_stores" DROP CONSTRAINT IF EXISTS fk_vm_resource_stores_creature;
ALTER TABLE aseman_core."vm_resource_stores" ADD CONSTRAINT fk_vm_resource_stores_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_vm_resource_stores_updated_at ON aseman_core."vm_resource_stores" (updated_at_micros, id);

ALTER TABLE aseman_core."vm_resource_entities" DROP CONSTRAINT IF EXISTS fk_vm_resource_entities_resource_store;
ALTER TABLE aseman_core."vm_resource_entities" ADD CONSTRAINT fk_vm_resource_entities_resource_store FOREIGN KEY ("resource_store") REFERENCES aseman_core."vm_resource_stores"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_vm_resource_entities_resource_store_entity_type_entity_ref ON aseman_core."vm_resource_entities" ("resource_store", "entity_type", "entity_ref") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_vm_resource_entities_updated_at ON aseman_core."vm_resource_entities" (updated_at_micros, id);

ALTER TABLE aseman_core."entity_configs" DROP CONSTRAINT IF EXISTS fk_entity_configs_entity;
ALTER TABLE aseman_core."entity_configs" ADD CONSTRAINT fk_entity_configs_entity FOREIGN KEY ("entity") REFERENCES aseman_core."entities"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_entity_configs_entity ON aseman_core."entity_configs" ("entity") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_entity_configs_updated_at ON aseman_core."entity_configs" (updated_at_micros, id);

ALTER TABLE aseman_core."entity_artifacts" DROP CONSTRAINT IF EXISTS fk_entity_artifacts_entity;
ALTER TABLE aseman_core."entity_artifacts" ADD CONSTRAINT fk_entity_artifacts_entity FOREIGN KEY ("entity") REFERENCES aseman_core."entities"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_entity_artifacts_entity_artifact_role ON aseman_core."entity_artifacts" ("entity", "artifact_role") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_entity_artifacts_updated_at ON aseman_core."entity_artifacts" (updated_at_micros, id);

ALTER TABLE aseman_core."creature_secrets" DROP CONSTRAINT IF EXISTS fk_creature_secrets_creature;
ALTER TABLE aseman_core."creature_secrets" ADD CONSTRAINT fk_creature_secrets_creature FOREIGN KEY ("creature") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_creature_secrets_creature_name ON aseman_core."creature_secrets" ("creature", "name") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_creature_secrets_updated_at ON aseman_core."creature_secrets" (updated_at_micros, id);

ALTER TABLE aseman_core."secret_grants" DROP CONSTRAINT IF EXISTS fk_secret_grants_secret;
ALTER TABLE aseman_core."secret_grants" ADD CONSTRAINT fk_secret_grants_secret FOREIGN KEY ("secret") REFERENCES aseman_core."creature_secrets"(id) ON DELETE CASCADE;
ALTER TABLE aseman_core."secret_grants" DROP CONSTRAINT IF EXISTS fk_secret_grants_grantee;
ALTER TABLE aseman_core."secret_grants" ADD CONSTRAINT fk_secret_grants_grantee FOREIGN KEY ("grantee") REFERENCES aseman_core."creatures"(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_secret_grants_secret_grantee_ref ON aseman_core."secret_grants" ("secret", "grantee_ref") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_secret_grants_updated_at ON aseman_core."secret_grants" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bridge_grants_token_digest ON aseman_core."bridge_grants" ("token_digest") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_bridge_grants_updated_at ON aseman_core."bridge_grants" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bridge_topics_topic ON aseman_core."bridge_topics" ("topic") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_bridge_topics_updated_at ON aseman_core."bridge_topics" (updated_at_micros, id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_legacy_identities_family_legacy_id ON aseman_core."legacy_identities" ("family", "legacy_id") WHERE NOT tombstone;
CREATE UNIQUE INDEX IF NOT EXISTS uq_legacy_identities_target_kind_target_id ON aseman_core."legacy_identities" ("target_kind", "target_id") WHERE NOT tombstone;
CREATE INDEX IF NOT EXISTS ix_legacy_identities_updated_at ON aseman_core."legacy_identities" (updated_at_micros, id);

COMMIT;
